// Map frontend snake_case → Discord.js camelCase
export const FLAG_MAP = {
  CREATE_INSTANT_INVITE: 'CreateInstantInvite',
  KICK_MEMBERS: 'KickMembers',
  BAN_MEMBERS: 'BanMembers',
  ADMINISTRATOR: 'Administrator',
  MANAGE_CHANNELS: 'ManageChannels',
  MANAGE_GUILD: 'ManageGuild',
  MANAGE_MESSAGES: 'ManageMessages',
  MANAGE_ROLES: 'ManageRoles',
  MANAGE_WEBHOOKS: 'ManageWebhooks',
  MANAGE_GUILD_EXPRESSIONS: 'ManageGuildExpressions',
  VIEW_CREATOR_MONETIZATION_ANALYTICS: 'ViewCreatorMonetizationAnalytics',

  MODERATE_MEMBERS: 'ModerateMembers',

  ADD_REACTIONS: 'AddReactions',
  VIEW_AUDIT_LOG: 'ViewAuditLog',
  PRIORITY_SPEAKER: 'PrioritySpeaker',
  STREAM: 'Stream',
  VIEW_CHANNEL: 'ViewChannel',
  SEND_MESSAGES: 'SendMessages',
  SEND_TTS_MESSAGES: 'SendTTSMessages',
  EMBED_LINKS: 'EmbedLinks',
  ATTACH_FILES: 'AttachFiles',
  READ_MESSAGE_HISTORY: 'ReadMessageHistory',
  MENTION_EVERYONE: 'MentionEveryone',
  USE_EXTERNAL_EMOJIS: 'UseExternalEmojis',
  VIEW_GUILD_INSIGHTS: 'ViewGuildInsights',
  CONNECT: 'Connect',
  SPEAK: 'Speak',
  MUTE_MEMBERS: 'MuteMembers',
  DEAFEN_MEMBERS: 'DeafenMembers',
  MOVE_MEMBERS: 'MoveMembers',
  USE_VAD: 'UseVAD',
  CHANGE_NICKNAME: 'ChangeNickname',
  MANAGE_NICKNAMES: 'ManageNicknames',
  USE_APPLICATION_COMMANDS: 'UseApplicationCommands',
  REQUEST_TO_SPEAK: 'RequestToSpeak',
  MANAGE_EVENTS: 'ManageEvents',
  MANAGE_THREADS: 'ManageThreads',
  CREATE_PUBLIC_THREADS: 'CreatePublicThreads',
  CREATE_PRIVATE_THREADS: 'CreatePrivateThreads',
  USE_EXTERNAL_STICKERS: 'UseExternalStickers',
  SEND_MESSAGES_IN_THREADS: 'SendMessagesInThreads',
  USE_EMBEDDED_ACTIVITIES: 'UseEmbeddedActivities',
  USE_SOUNDBOARD: 'UseSoundboard',
  CREATE_GUILD_EXPRESSIONS: 'CreateGuildExpressions',
  CREATE_EVENTS: 'CreateEvents',
  USE_EXTERNAL_SOUNDS: 'UseExternalSounds',
  SEND_VOICE_MESSAGES: 'SendVoiceMessages',
  SEND_POLLS: 'SendPolls',
  USE_EXTERNAL_APPS: 'UseExternalApps'
}
